### ISSUE TITLE
Improve current API by adding more tests

### ISSUE THREAD

**Issue by TG1999** [nexB/fetchcode#19]
In PR #4 basic API has been build, but it need more tests. So this issue can be solved by adding more tests for it and making the API more full proof.

**Comment by majurg** [comment]
@TG1999 So the goal here is for fetchcode to be able to any type of URL you can throw at it. 

So for a quick list, here are some it should support:
1) `http://`
2) `https://`
3) `git://`
4) `svn://`
5) `ftp://`
6) `stfp://`

There are probably more that I am missing, but these are a good start. @pombredanne might also have more for you.

As for finding valid examples of each of these schemes, that is up to you. It should be easy enough to find a number of these in the wild that you can use for test cases.

**Comment by TG1999** [comment]
@majurg okay, I am getting you. So we can cover all the VCS based URLs later on, when I will be working on reusing pip's VCS module. For now I will try to cover all non VCS(git, hg, svn, bzr) based URLs. Sounds good ? :D

**Comment by majurg** [comment]
@TG1999 Yes. I would also look at the python3 standard library to see if there is applicable functions.

**Comment by TG1999** [comment]
Cool 🙌 @majurg
